#!/usr/bin/env python3
# created: 2026-05-12T17:00:00Z
# cycle: 38
# run_id: run-2026-05-11T121649Z
# agent: worker
# milestone: M-LIVECOLLECT-1
"""Build the production-side evidence collector contract tables."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
GATE_SCHEMA = DATA / "gate_evidence_artifact_schema.csv"

OUT_CAPABILITY = DATA / "live_collector_capability_matrix.csv"
OUT_INPUTS = DATA / "live_collector_required_operator_inputs.csv"
OUT_MAPPING = DATA / "live_collector_artifact_mapping.csv"
OUT_PREFLIGHT = DATA / "live_collector_preflight_schema.csv"

SOURCE_CLASSES = {
    "root_enrollment": ("operator_supplied", "deployment_root_identity_file", "deployment root identity must come from operator enrollment material"),
    "attestation_envelope": ("external_attestation", "external_attestation_file", "attestation must be supplied by hardware/KMS/HSM or external attester, not generated by this collector"),
    "trust_policy": ("operator_supplied", "operator_trust_policy_file", "operator trust policy must be supplied and signed outside the collector"),
    "intake_custody": ("collector_observed", "bundle_manifest_file", "collector can observe local manifest and output custody path"),
    "adapter_conformance": ("collector_observed", "adapter_conformance_file", "collector can bind an adapter conformance report produced by the adapter/conformance kit"),
    "timebase_integrity": ("collector_observed", "time_source_file", "collector can observe time source freshness and measurement window"),
    "redaction_integrity": ("collector_observed", "redaction_report_file", "collector can bind redaction evaluator output"),
    "evidence_gatechain": ("derived_from_prior_gate", "gatechain_report_file", "derived replay consumes prior gate outputs"),
    "uncertainty_qualification": ("collector_observed", "uncertainty_report_file", "collector can bind confidence report produced from captured telemetry"),
    "causal_attribution": ("operator_supplied", "causal_control_report_file", "control-arm/covariate material must be supplied by experiment owner"),
    "dc001_dc002_threshold_replay": ("collector_observed", "threshold_replay_file", "collector can bind threshold replay output from telemetry counters"),
    "planner_readiness_boundary": ("derived_from_prior_gate", "planner_boundary_file", "derived boundary consumes threshold, security, and planner outputs"),
    "final_handoff_traceability": ("operator_supplied", "handoff_traceability_file", "operator must supply final claim-to-evidence traceability material"),
}

PREFLIGHT_CHECKS = [
    ("production_root_marker", "required_for_production", "production root marker file exists and declares production_root=true"),
    ("deployment_root_identity_file", "required_for_production", "operator-supplied deployment root identity exists"),
    ("collector_identity_file", "required_for_all_emission", "collector identity exists and binds collector_id"),
    ("operator_trust_policy_file", "required_for_production", "operator trust policy exists and is externally produced"),
    ("external_attestation_file", "required_for_production", "external attestation exists and is not collector-generated"),
    ("telemetry_counter_source_file", "required_for_production", "counter source file exists for measured telemetry"),
    ("time_source_file", "required_for_all_emission", "time source exists and is fresh"),
    ("artifact_output_root", "required_for_all_emission", "output root is writable"),
    ("self_attestation_guard", "required_for_production", "attestation producer differs from collector producer"),
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"{path.relative_to(ROOT)} is empty")
    return rows


def write_csv(path: Path, rows: list[dict[str, object]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})
    print(f"wrote {path.relative_to(ROOT)} rows={len(rows)}")


def capability_rows(schema: list[dict[str, str]]) -> list[dict[str, object]]:
    rows = []
    for gate in schema:
        gate_name = gate["gate_name"]
        source_class, input_field, reason = SOURCE_CLASSES[gate_name]
        rows.append(
            {
                "gate_order": gate["order"],
                "gate_name": gate_name,
                "collection_source_class": source_class,
                "required_input_or_observation": input_field,
                "can_collector_generate_directly": str(source_class == "collector_observed").lower(),
                "requires_operator_or_external_material": str(source_class in {"operator_supplied", "external_attestation"}).lower(),
                "self_attestation_risk": str(gate_name in {"attestation_envelope", "trust_policy", "root_enrollment"}).lower(),
                "collection_boundary": reason,
            }
        )
    return rows


def operator_input_rows(schema: list[dict[str, str]]) -> list[dict[str, object]]:
    rows = []
    for gate in schema:
        gate_name = gate["gate_name"]
        source_class, input_field, reason = SOURCE_CLASSES[gate_name]
        if source_class in {"operator_supplied", "external_attestation"}:
            rows.append(
                {
                    "gate_name": gate_name,
                    "input_field": input_field,
                    "source_class": source_class,
                    "required_for_production_label": "true",
                    "collector_may_synthesize": "false",
                    "fail_closed_reason_if_missing": f"missing_{input_field}",
                    "rationale": reason,
                }
            )
    return rows


def mapping_rows(schema: list[dict[str, str]]) -> list[dict[str, object]]:
    rows = []
    for gate in schema:
        gate_name = gate["gate_name"]
        source_class, input_field, _ = SOURCE_CLASSES[gate_name]
        rows.append(
            {
                "gate_order": gate["order"],
                "gate_name": gate_name,
                "source_class": source_class,
                "source_input_field": input_field,
                "artifact_filename": f"{gate_name}.json",
                "manifest_boolean_field": gate["manifest_boolean_field"],
                "manifest_evidence_path_field": gate["evidence_path_field"],
                "manifest_digest_field": gate["digest_field"],
                "required_payload_fields": gate["required_payload_fields"],
                "upstream_dependency": gate["upstream_dependency"],
            }
        )
    return rows


def preflight_rows() -> list[dict[str, object]]:
    rows = [
        {
            "check_name": name,
            "requirement_level": level,
            "pass_condition": condition,
            "failure_state": {
                "production_root_marker": "not_running_in_production_root",
                "deployment_root_identity_file": "operator_material_missing",
                "collector_identity_file": "collector_capability_missing",
                "operator_trust_policy_file": "operator_material_missing",
                "external_attestation_file": "operator_material_missing",
                "telemetry_counter_source_file": "collector_capability_missing",
                "time_source_file": "collector_capability_missing",
                "artifact_output_root": "collector_capability_missing",
                "self_attestation_guard": "operator_material_missing",
            }[name],
            "claim_credit_effect": "none",
        }
        for name, level, condition in PREFLIGHT_CHECKS
    ]
    for gate_name, (source_class, input_field, reason) in SOURCE_CLASSES.items():
        rows.append(
            {
                "check_name": f"source_material:{input_field}",
                "requirement_level": "required_for_production_artifact_emission",
                "pass_condition": f"{input_field} exists and is the source material for {gate_name}: {reason}",
                "failure_state": "operator_material_missing"
                if source_class in {"operator_supplied", "external_attestation"}
                else "collector_capability_missing",
                "claim_credit_effect": "none",
            }
        )
    return rows


def main() -> None:
    schema = read_csv(GATE_SCHEMA)
    write_csv(
        OUT_CAPABILITY,
        capability_rows(schema),
        [
            "gate_order",
            "gate_name",
            "collection_source_class",
            "required_input_or_observation",
            "can_collector_generate_directly",
            "requires_operator_or_external_material",
            "self_attestation_risk",
            "collection_boundary",
        ],
    )
    write_csv(
        OUT_INPUTS,
        operator_input_rows(schema),
        [
            "gate_name",
            "input_field",
            "source_class",
            "required_for_production_label",
            "collector_may_synthesize",
            "fail_closed_reason_if_missing",
            "rationale",
        ],
    )
    write_csv(
        OUT_MAPPING,
        mapping_rows(schema),
        [
            "gate_order",
            "gate_name",
            "source_class",
            "source_input_field",
            "artifact_filename",
            "manifest_boolean_field",
            "manifest_evidence_path_field",
            "manifest_digest_field",
            "required_payload_fields",
            "upstream_dependency",
        ],
    )
    write_csv(OUT_PREFLIGHT, preflight_rows(), ["check_name", "requirement_level", "pass_condition", "failure_state", "claim_credit_effect"])


if __name__ == "__main__":
    main()
