#!/usr/bin/python3
"""c81 one-shot POR registration: insert c81 sub-leaf rows inline in the `## Milestones` parseable region
(before `## Sub-milestones`). Idempotent. Retained in-tree per c14+ emitter-exemption pattern."""
import json, os, sys
from pathlib import Path
os.chdir(Path(__file__).resolve().parent.parent)
POR = Path("plan_of_record.md")
P = "M-V5-CORPUS-1"
C = Path("data/v5/corpus")


def main() -> int:
    fals = json.loads((C / "tempo_v5c_falsification.json").read_text())
    ps = fals["per_song"]
    fid = json.loads((C / "252eb21ce7df7328/reindex_fidelity_c81.json").read_text())
    grv = json.loads(Path("data/v5/rules/groove_v5.json").read_text())
    venv = json.loads(Path("data/v5/ear/venv_build_c81.json").read_text())
    chain_p = Path("data/v5/rules/harmony_markov_v5.json")
    gated_p = Path("data/v5/rules/harmony_v5_gated.json")
    other = fid["per_stem"]["other"]
    rows = [
     (f"{P}/transcription-liveness-c81", "G4", "c81 P0.1: PID 5201 verified ALIVE via `os.kill(pid, 0)` (ps/`/proc` are approval-gated in this sandbox) + log advancing on Rome muscriptor; record `data/v5/logs/c81_p0_liveness.txt`. df 86.9 % at open (< 90 abort); driver untouched (no SIGSTOP/SIGCONT issued because no pip ran — see ear-venv-blocked-disk-c81).", "Liveness file exists; job alive; no df >= 90 %.", f"{P}/transcription-liveness-c80"),
     (f"{P}/reindex-hygiene-c81", "G4", "c81 P0.2-P0.6 closes the c80 lossy-pointer gap: every landed song re-indexed (PD 2026 other starts -> 2023 paired / 3 unpaired; Rome when landed) with additive sidecar `canonical_v5_reindexed_sha256.json` next to each `transcription_manifest.json` (c79/c80 manifest bytes untouched); `scripts/v5/harmony_v5.py` preference tuple is lossless-only (`canonical_v5c_reindexed`, `canonical_v5_reindexed`) and raises `MissingReindexError('MISSING_REINDEX: <sha16> …')` — `canonical_midi_full` removed, docstring fixed; NEW `scripts/v5/reindex_hook.py` (`post_canonicalize` + idempotent `reindex_landed`) called by `transcribe_full_length.py` after the manifest write so later landings are lossless at birth (PID 5201 runs the OLD image; the catch-up loop covers landings until the natural restart — driver NOT restarted); `tempo_v5b_summary_c81.tsv` adds `anchor_source` with WIG anchor 99.384 (`librosa_full_mix_c79`), c80 TSV untouched. str-supersedes the manifest-pointer clause of `canonical-midi-index-collision-c80`.", "No consumer path to canonical_midi_full; sidecars match disk; hook fixture test green.", f"{P}/canonical-midi-index-collision-c80"),
     ("M-V5-EAR-1/ear-venv-blocked-disk-c81", "G3", f"c81 P1 **VENV_BLOCKED_DISK** (`data/v5/ear/venv_build_c81.json`): df used {venv['df']['used_pct_df_semantics']} %, avail {venv['df']['avail_user_gb']} GB (brief >= 3.5 GB gate passes) BUT the driver's binding 90 % abort ceiling leaves only {venv['arithmetic']['consumable_before_ceiling_gb']} GB consumable; the pinned 2.36 GB build would read {venv['arithmetic']['post_build_used_pct']} % (+VGGish weights {venv['arithmetic']['post_build_plus_vggish_used_pct']} %) — the driver's next `df_check` would FD-1-abort the in-flight song and stop the 26-song job; SIGSTOP/SIGCONT cannot change the arithmetic (c79 precedent 92.2 %). No pip run; no pause exercised; main-env pip-freeze sha 90ed1d9f… pre==post. Probe `scripts/v5/ear_probe_v5.py` written (READ-ONLY c74 extractor by subprocess, x2 fresh mkdtemp, pre-declared enum) — records `EAR_VENV_ABSENT` (exit 3) this cycle. ONE-LINE OPERATOR REQUEST: authority over `/root/.local` ({venv['root_local_bytes_untouched']/1e9:.2f} GB, outside the workspace) — freed, post-build usage would be ~87 % and the venv + probe fit. P2-P4 proceeded.", "Decision JSON with arithmetic + operator line; probe enum recorded; main env unchanged.", "M-V5-EAR-1/ear-venv-headroom-c80"),
     (f"{P}/tempo_v5c-preregistered-c81", "G4", "c81 P2: `data/v5/corpus/tempo_v5c_preregistration.json` written BEFORE any per-song output (mtime gate verified by the verdict script + test_03). Axis varied: harmonic terms T/2 and 2T read DIRECTLY from the autocorrelation at the exact fractional lag by linear interpolation (0 only if lag < 1 or beyond the autocorrelation) — no candidate-band restriction. Held constant: candidates = local maxima in [40,240], pick band [70,180], weights (1, ½, ½), tiebreak, corpus, env pin. Targets identical to c79/c80. Secondary check: Rome s(lag 17) and s(lag 25) explicit. Third and FINAL unaided attempt; meta-gate: RULES_OUT -> c82 mechanism probe, no fourth criterion. `scripts/v5/tempo_v5c.py` + `tempo_v5c_verdict.py` new siblings (READ-ONLY imports of tempo_v5 / tempo_v5b helpers).", "Prereg mtime precedes every tempo_v5c.json; 26/26 scored; byte-det x2.", f"{P}/tempo_v5b-verdict-c80"),
     (f"{P}/tempo_v5c-verdict-c81", "G4", f"c81 P2 FROZEN VERDICT = **{fals['verdict']}** (`tempo_v5c_falsification.json`). 4/5 anchors HIT: WIG {ps['252eb21ce7df7328']['bpm_v5c']}; CG {ps['31a164f845f8e27e']['bpm_v5c']} (+1.56); **Peach Dream RECOVERED 80.75 -> {ps['88d247468cb6d49f']['bpm_v5c']}** (s 1.379 vs 1.222 — the c80-diagnosed mechanism confirmed: the T/2 term at lag 10.5 now reads 0.640); **Rome HELD 152.00** (s(lag 17)=1.401 > s(lag 25)=1.112; hemiola resolved). MISSED: **Disco A 80.75 unchanged** — s(lag 32)=1.1913 vs s(lag 21, 123.05)=1.1851, a 0.006 margin (ac_T 0.660 vs 0.632; the hemiola lag's 2T term 0.609 nearly equals the beat's T/2 0.640). Non-anchor flips 6/21 (29 %). Byte-det x2 27/27. FD-1: no retune; meta-gate fires (three consecutive falsifications) -> c82 mechanism probe (per-song ac dump + beat-tracker on drums stem vs full mix) before any criterion. Figure `fig_tempo_v5c_scores.png` (PD / Disco A / Rome with interpolated harmonic points) from `plot_tempo_v5c_scores.py`. Invalidated hypothesis recorded: 'autocorr-direct harmonic sum resolves ALL five anchors' — it resolves four, and the fifth fails inside the score's own resolution, not by mechanism.", "Verdict ∈ frozen enum; per-song hits verbatim; no retune; Rome table present.", f"{P}/tempo_v5c-preregistered-c81"),
     (f"{P}/recanonicalize-still-blocked-c81", "G4", "c81 P2 RULES_OUT branch: `recanonicalization_blocked.json` (c80) left UNCHANGED — Peach Dream + Disco A remain MUST-NOT-CONSUME for rules; no `canonical_v5c_reindexed/` directory created; `scripts/v5/recanonicalize_tempo.py` NOT written (its trigger did not fire). Note for c82: PD's v5c value equals its anchor, but adopting it selectively would be a post-hoc criterion (FD-1); it stays blocked until a criterion is SUPPORTED or the c82 mechanism probe grounds an operator decision.", "Blocked file byte-identical to c80; no v5c canonical dirs.", f"{P}/tempo_v5c-verdict-c81"),
     (f"{P}/reindex-fidelity-c81", "G4", f"c81 P3 (M-3) `data/v5/corpus/252eb21ce7df7328/reindex_fidelity_c81.json`: WIG `canonical_v5_reindexed/` restricted to t∈[72.77,102.77] s vs the c21 single-chunk operator-section canonical MIDI (both READ-ONLY; seconds via each file's own tempo meta — the c21 files are serialized at 50.174 BPM). Pre-declared verdict = **{fid['verdict']}**: onset F1 (pitch-equal, ±50 ms) drums 0.55 / bass 0.95 / other 0.746 / piano 0.44 / vocals 0.62 / full_mix 0.53 (pitch-agnostic 0.79/1.0/0.85/0.52/0.70/0.68); median |Δduration| on matched onsets: drums 0.1 ms, bass 1.5 ms (n=19, below the 20 gate), piano 18 ms, vocals 20 ms, full_mix 2 ms — all ≤ 75 ms — but **other {other['dduration_median_s']*1000:.0f} ms** (n=305; p90 1.47 s). DIAGNOSTIC (not part of the verdict): pairing-ambiguity fraction (starts in the window with >1 candidate end of the same chunk-local index within 30 s) = other {other['pairing_ambiguity_diagnostic']['ambiguous_fraction']:.2f}, piano 1.00, full_mix 0.86, vocals 0.51, drums 0.29, bass 0.00; median note duration full/section other 0.465/0.299 s. FINDING: onsets are lossless (M-3 (a) holds where the two transcriptions agree); the c80 greedy start/end pairing over-assigns durations on the dense polyphonic `other` stem where 90 % of pairings are ambiguous. Consequence: harmony_v5's duration-weighted PCPs on `other` carry inflated durations. c82 handoff: chunk-window-constrained pairing (a start at t belongs to chunk ⌊t/25⌋; only ends inside that chunk's [25k, 25k+30] window are eligible) — pre-declare and re-measure with this same script. Byte-det x2 holds.", "JSON with per-stem F1 + |Δduration| medians + verdict from the pre-declared enum; byte-det x2.", f"{P}/canonical-midi-index-collision-c80"),
     ("M-V5-RULES-1/groove_v5-first-data-c81", "G4", f"c81 P4 (OPERATOR #3 first data) `scripts/v5/groove_v5.py` -> `data/v5/rules/groove_v5.json` on WIG + CG `canonical_v5_reindexed/` drums (GM kick 35/36, snare 37-40, hat 42/44/46) + bass; 16th grid (120 ticks), per-bar 16-bit patterns, corpus bars = bars with ≥1 drum onset ({grv['corpus_stats']['n_bars']} bars); conditionals P(snare|kick), P(hat|kick,snare), P(bass|kick) counts + row-normalized; 64 bars sampled by SHA-256 inverse-CDF (no PRNG). Pre-declared verdict = **{grv['verdict']}**: backbeat ratio corpus {grv['corpus_stats']['backbeat_ratio']:.3f} vs sampled {grv['sample_stats']['backbeat_ratio']:.3f} (Δ {grv['validation']['backbeat_ratio']['abs_diff']:.3f} ≤ 0.10); bass-kick lock {grv['corpus_stats']['bass_kick_lock']:.3f} vs {grv['sample_stats']['bass_kick_lock']:.3f} (Δ {grv['validation']['bass_kick_lock']['abs_diff']:.3f}); sampled distinct kick {grv['sample_stats']['distinct_kick_patterns']} / bass {grv['sample_stats']['distinct_bass_patterns']}; contexts {grv['table_context_counts']}. HONEST DISCLOSURES: (a) the corpus backbeat ratio is only 0.14 — MuScriptor snare onsets (incl. GM 37/39/40) rarely land exactly on 16th slots 4/12 at bpm_v5, so 'backbeat' as pre-declared measures grid-exact snares, not the audible backbeat; (b) with 124 distinct kick patterns over 172 bars the conditional tables are near one-to-one — the n=2 model largely replays corpus bars (non-degenerate by the pre-declared test, low generalization); more songs are the fix, not a re-tune. Data-existence only; nothing fed to a generator. Byte-det x2 holds.", "Verdict from the pre-declared enum on WIG + CG; byte-det x2; blocked songs refused.", "M-V5-CORPUS-1/reindex-hygiene-c81"),
    ]
    if chain_p.exists():
        mk = json.loads(chain_p.read_text())
        rows.append(("M-V5-RULES-1/harmony_v5-first-data-c81", "G4", f"c81 P4.1: patched `harmony_v5.py` re-run on {mk['gate']['n_used']} unblocked reindexed songs {mk['gate']['used']} -> `data/v5/rules/harmony_markov_v5.json`: {len(mk['states'])} functional states; max stationary {mk['max_stationary_state']} = {mk['max_stationary_mass']}; qualities with ≥ 8 segments {mk['qualities_with_count_ge_threshold']}; pre-declared (c80) degeneracy verdict **{mk['degeneracy_verdict']}**. Per-song keys: " + "; ".join(f"{v['title']} {v['key']['tonic_name']} {v['key']['mode']}" for v in mk['per_song'].values()) + ". Caveat from reindex-fidelity-c81: `other`-stem durations are inflated by the greedy pairing (duration-weighted PCPs). PD + Disco A never consumed (blocked).", "Chain emitted with pre-declared verdict; ≥3 unblocked songs; nothing fed to a generator.", "M-V5-RULES-1/harmony_v5-gated-c80"))
    else:
        g = json.loads(gated_p.read_text())
        rows.append(("M-V5-RULES-1/harmony_v5-gated-c81", "G4", f"c81 P4.1: patched `harmony_v5.py` (lossless-only, MISSING_REINDEX) re-run -> still GATED: {g['n_used']} unblocked landed songs {g['used']} (< 3); blocked-skipped {g['blocked_skipped']}; Rome not landed+reindexed at emit time. Official run re-executes unchanged once Rome lands (the driver hook / catch-up loop reindexes it).", "Gated record with count.", "M-V5-RULES-1/harmony_v5-gated-c80"))
    rows += [
     ("_plan/register-c81-sub-leaves", "G1", "c81 POR registration row: c81 sub-leaves inserted inline in the `## Milestones` parseable region via `tools/_register_c81_por_rows.py` (idempotent; per-song `<sha16>-reindexed-c81` rows generated from on-disk sidecars). M-V5-CORPUS-1: 4 of 26 landed (WIG, CG, PD, Rome), all lossless + sidecar; M-V5-EAR-1: venv VENV_BLOCKED_DISK (operator line); M-V5-RULES-1: harmony per row above, groove first data on 2 songs; PD + Disco A remain blocked.", "Rows added.", "—"),
     ("_infra/adopt-cycle81-tests", "G1", "c81 test-adoption: `tests/test_reindex_hygiene_c81.py` (5: harmony refuses lossy dir + preference tuple; sidecar SHAs + lossless-by-count on every landed song; hook on a synthetic two-chunk fixture — serializer keeps 3/6, hook recovers 6/6, catch-up idempotent; driver calls hook after manifest + AST; c81 TSV anchor_source) + `tests/test_tempo_v5c.py` (6: on-disk PD lag-21 T/2 interpolated > 0; synthetic period-21 3:2 picks T; prereg mtime gate + enum + RULES_OUT branch keeps blocked file; Rome hemiola table; byte-det; AST on 6 c81 scripts) + `tests/test_groove_v5.py` (3: synthetic backbeat corpus reproduces 1.0/1.0; degenerate fixture rejected; hash-uniform + inverse-CDF) + `tests/test_ear_venv_c81.py` (3: decision record shape; main-env freeze unchanged; probe enum + venv-absent exit 3). 17 new + 51 regression = 68 cross-cycle.", "17/17 new + 51/51 regression green.", "—"),
     ("_archive/cycle-81-scratch", "G1", "c81 scratch archival: `tools/_emit_c81_ledger_events.py` + `tools/_register_c81_por_rows.py` retained in-tree per emitter-exemption pattern; session scratchpad runners (p0_liveness, p0_6_summary_c81, p1_venv_decision, bytedet_v5c, bytedet_p3_p4, run_tests) not in workspace; `data/v5/corpus/plot_tempo_v5c_scores.py` co-located with its data + figure.", "No workspace scratch to archive.", "—"),
     ("_run/cycle_81_closed", "G1", "c81 CLOSED — v5 REOPENING cycle 3. See ledger event narrative for the 9-header closing summary.", "Cycle rollup after named sub-leaves.", "—"),
    ]
    for side_p in sorted(C.glob("*/canonical_v5_reindexed_sha256.json")):
        s = side_p.parent.name
        rm = json.loads((C / s / "canonical_v5_reindexed/reindex_manifest.json").read_text())
        tm = json.loads((C / s / "transcription_manifest.json").read_text())
        tot = {k: sum(v[k] for v in rm["probes"].values()) for k in ("n_starts_in", "n_paired", "n_unpaired_starts")}
        rows.append((f"{P}/{s}-reindexed-c81", "G4", f"c81 per-song lossless record: {tm.get('title')} ({s}, bpm_v5 {tm['bpm_v5']}): `canonical_v5_reindexed/` starts {tot['n_starts_in']} -> paired {tot['n_paired']} / unpaired {tot['n_unpaired_starts']} (100 ms synthetic); sidecar `canonical_v5_reindexed_sha256.json` (reindex_manifest sha {json.loads(side_p.read_text())['reindex_manifest_sha256'][:12]}…); stage-cache manifests + reindexed MIDI/JSON adopted as artifacts.", "Sidecar SHAs match disk; MIDI note_on == JSON starts.", f"{P}/reindex-hygiene-c81"))
    txt = POR.read_text()
    lines = txt.splitlines(keepends=True)
    idx = next(i for i, l in enumerate(lines) if l.startswith("## Sub-milestones"))
    existing = {l.split("|")[1].strip() for l in lines[:idx] if l.startswith("| ")}
    new = [f"| {mid} | {goal} | {desc} | {crit} | {deps} |\n" for mid, goal, desc, crit, deps in rows if mid not in existing]
    if not new:
        print("IDEMPOTENT: all c81 POR rows present"); return 0
    ins = idx
    while ins > 0 and lines[ins - 1].strip() == "":
        ins -= 1
    lines[ins:ins] = new
    POR.write_text("".join(lines))
    print(f"inserted {len(new)} rows before line {ins + 1}: {[r.split('|')[1].strip() for r in new]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
